# Generated by Django 3.1.3 on 2020-11-17 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.TextField()),
                ('version', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MkiFirstRequestResearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_research', models.CharField(blank=True, max_length=100)),
                ('owner_request', models.CharField(blank=True, max_length=50)),
                ('date_created', models.DateTimeField(blank=True, max_length=30)),
                ('main_researcher', models.CharField(blank=True, max_length=50)),
                ('list_members', models.CharField(blank=True, max_length=100)),
                ('ver_bio', models.CharField(blank=True, max_length=100)),
                ('predsedatel_accepted', models.CharField(blank=True, max_length=10)),
                ('secretar_accepted', models.CharField(blank=True, max_length=10)),
                ('accept_research', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accept_research', to='ResearchManage.files')),
                ('adversting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adversting', to='ResearchManage.files')),
                ('another_doc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='another_doc', to='ResearchManage.files')),
                ('cast_research', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cast_research', to='ResearchManage.files')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='ResearchManage.files')),
                ('form_inf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_inf', to='ResearchManage.files')),
                ('protocol_research', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='protocol_research', to='ResearchManage.files')),
                ('write_objects', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='write_objects', to='ResearchManage.files')),
            ],
        ),
    ]
