# Generated by Django 3.1.3 on 2020-11-17 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ResearchManage', '0002_auto_20201117_1348'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Files',
        ),
        migrations.AlterField(
            model_name='mkifirstrequestresearch',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
