# Generated by Django 3.1.3 on 2020-11-17 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ResearchManage', '0003_auto_20201117_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mkifirstrequestresearch',
            name='main_researcher',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='UserControl.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mkifirstrequestresearch',
            name='owner',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
