# Generated by Django 3.1.3 on 2020-11-18 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ResearchManage', '0004_auto_20201117_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mkifirstrequestresearch',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='UserControl.user'),
            preserve_default=False,
        ),
    ]
