# Generated by Django 3.1.3 on 2020-11-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResearchManage', '0005_auto_20201118_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='mkifirstrequestresearch',
            name='date_created',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
