# Generated by Django 3.1.7 on 2021-02-26 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ResearchManage', '0008_auto_20210225_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='mkifirstrequestresearch',
            name='exprert',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='username_expert', to='UserControl.user'),
            preserve_default=False,
        ),
    ]
