# Generated by Django 3.1.7 on 2021-02-26 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ResearchManage', '0009_mkifirstrequestresearch_exprert'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mkifirstrequestresearch',
            old_name='exprert',
            new_name='expert',
        ),
    ]
