# Generated by Django 3.1.7 on 2021-03-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResearchManage', '0012_auto_20210302_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mkifirstrequestresearch',
            name='accept_research_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mkifirstrequestresearch',
            name='another_doc_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mkifirstrequestresearch',
            name='cast_researcher_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mkifirstrequestresearch',
            name='contract_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mkifirstrequestresearch',
            name='date_created',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mkifirstrequestresearch',
            name='form_inf_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mkifirstrequestresearch',
            name='protocol_research_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
