# Generated by Django 3.1.7 on 2021-03-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResearchManage', '0015_auto_20210303_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='mkifirstrequestresearch',
            name='protocol_number',
            field=models.CharField(default='12321', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mkifirstrequestresearch',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
