# Generated by Django 3.1.7 on 2021-03-05 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserControl', '0010_pi_birthday'),
        ('ResearchManage', '0018_remove_mkifirstrequestresearch_main_researcher'),
    ]

    operations = [
        migrations.AddField(
            model_name='mkifirstrequestresearch',
            name='main_researcher',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='UserControl.pi_birthday'),
            preserve_default=False,
        ),
    ]
