# Generated by Django 3.1.7 on 2021-03-05 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserControl', '0010_pi_birthday'),
        ('ResearchManage', '0019_mkifirstrequestresearch_main_researcher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mkifirstrequestresearch',
            name='main_researcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FIO_res', to='UserControl.pi_birthday'),
        ),
    ]
