# Generated by Django 3.1.7 on 2021-03-09 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserControl', '0011_auto_20210309_1422'),
        ('ResearchManage', '0020_auto_20210305_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mkifirstrequestresearch',
            name='main_researcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FIOS', to='UserControl.pi_birthday'),
        ),
    ]
