# Generated by Django 3.1.7 on 2021-03-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResearchManage', '0021_auto_20210309_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mkifirstrequestresearch',
            name='accept_research',
            field=models.FileField(default='E', upload_to='temp/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mkifirstrequestresearch',
            name='accept_research_date',
            field=models.CharField(default='E', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mkifirstrequestresearch',
            name='accept_research_version',
            field=models.CharField(default='e', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mkifirstrequestresearch',
            name='cast_researcher',
            field=models.FileField(default='e', upload_to='temp/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mkifirstrequestresearch',
            name='cast_researcher_date',
            field=models.CharField(default='e', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mkifirstrequestresearch',
            name='cast_researcher_version',
            field=models.CharField(default='e', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mkifirstrequestresearch',
            name='contract',
            field=models.FileField(default='e', upload_to='contract/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mkifirstrequestresearch',
            name='contract_date',
            field=models.CharField(default='e', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mkifirstrequestresearch',
            name='date_created',
            field=models.CharField(default='e', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mkifirstrequestresearch',
            name='document',
            field=models.FileField(default='e', upload_to='temp/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mkifirstrequestresearch',
            name='form_inf',
            field=models.FileField(default='e', upload_to='temp/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mkifirstrequestresearch',
            name='form_inf_date',
            field=models.CharField(default='e', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mkifirstrequestresearch',
            name='form_inf_version',
            field=models.CharField(default='e', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mkifirstrequestresearch',
            name='list_members',
            field=models.FileField(default='e', upload_to='temp/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mkifirstrequestresearch',
            name='protocol_research',
            field=models.FileField(default='e', upload_to='temp/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mkifirstrequestresearch',
            name='protocol_research_date',
            field=models.CharField(default='e', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mkifirstrequestresearch',
            name='protocol_research_version',
            field=models.CharField(default='e', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mkifirstrequestresearch',
            name='secretar_accepted',
            field=models.CharField(default='e', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mkifirstrequestresearch',
            name='status',
            field=models.CharField(default='e', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mkifirstrequestresearch',
            name='ver_bio',
            field=models.CharField(default='e', max_length=50),
            preserve_default=False,
        ),
    ]
