# Generated by Django 3.1.7 on 2021-03-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResearchManage', '0022_auto_20210309_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestsResearchsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
