# Generated by Django 3.1.7 on 2021-03-15 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ResearchManage', '0023_requestsresearchslist'),
    ]

    operations = [
        migrations.AddField(
            model_name='mkifirstrequestresearch',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ResearchManage.requestsresearchslist'),
            preserve_default=False,
        ),
    ]
