# Generated by Django 3.1.7 on 2021-03-17 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ResearchManage', '0024_mkifirstrequestresearch_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedProductRequestResearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formular_request', models.CharField(max_length=100)),
                ('teamList', models.CharField(max_length=100)),
                ('version_science_bio', models.CharField(max_length=100)),
                ('permission_FS', models.CharField(max_length=100)),
                ('conclusion_ethics', models.CharField(max_length=100)),
                ('program_klin_research', models.CharField(max_length=100)),
                ('form_inf_list', models.CharField(max_length=100)),
                ('registration_cards', models.CharField(max_length=100)),
                ('another_materials', models.CharField(max_length=100)),
                ('info_payout', models.CharField(max_length=100)),
                ('brochure_researcher', models.CharField(max_length=100)),
                ('rukovodstvo', models.CharField(max_length=100)),
                ('technical_file', models.CharField(max_length=100)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ResearchManage.requestsresearchslist')),
            ],
        ),
    ]
