# Generated by Django 3.1.7 on 2021-03-18 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResearchManage', '0025_medproductrequestresearch'),
    ]

    operations = [
        migrations.AddField(
            model_name='medproductrequestresearch',
            name='another_doc_expertize',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medproductrequestresearch',
            name='dublicat_dogovor',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medproductrequestresearch',
            name='info_med_company',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medproductrequestresearch',
            name='last_solutions',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medproductrequestresearch',
            name='polozhenie_o_soglasii',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
