# Generated by Django 3.1.7 on 2021-03-18 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ResearchManage', '0026_auto_20210318_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='medproductrequestresearch',
            name='date_created',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medproductrequestresearch',
            name='expert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='username_expert_med', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medproductrequestresearch',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='owner_med', to='UserControl.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medproductrequestresearch',
            name='secretar_accepted',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medproductrequestresearch',
            name='status',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
