# Generated by Django 3.1.7 on 2021-03-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResearchManage', '0028_auto_20210319_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='mkifirstrequestresearch',
            name='condition',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
