# Generated by Django 3.1.7 on 2021-03-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResearchManage', '0029_mkifirstrequestresearch_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='mkifirstrequestresearch',
            name='acceptedOnMeeting',
            field=models.CharField(default='False', max_length=20),
            preserve_default=False,
        ),
    ]
