# Generated by Django 3.1.7 on 2021-03-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResearchManage', '0030_mkifirstrequestresearch_acceptedonmeeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='medproductrequestresearch',
            name='acceptedOnMeeting',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
