# Generated by Django 3.1.7 on 2021-04-07 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResearchManage', '0033_auto_20210407_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='mkifirstrequestresearch',
            name='addedInMeeting',
            field=models.CharField(default='False', max_length=10),
            preserve_default=False,
        ),
    ]
