# Generated by Django 3.1.7 on 2021-04-19 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResearchManage', '0037_auto_20210419_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConflictsInterests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=100)),
                ('id_research', models.CharField(max_length=100)),
                ('type_research', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'ConflictsInterests',
                'verbose_name_plural': 'ConflictsInterestss',
            },
        ),
    ]
