# Generated by Django 3.1.7 on 2021-04-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResearchManage', '0040_auto_20210426_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='logaboutresearch',
            name='id_research',
            field=models.CharField(default=79, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logaboutresearch',
            name='type_research',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='logaboutresearch',
            name='condition',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
