# Generated by Django 3.1.7 on 2021-04-26 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResearchManage', '0041_auto_20210426_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mkifirstrequestresearch',
            name='condition',
        ),
        migrations.AlterField(
            model_name='logaboutresearch',
            name='id_research',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='logaboutresearch',
            name='type_research',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
