# Generated by Django 3.1.7 on 2021-04-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResearchManage', '0042_auto_20210426_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='logaboutresearch',
            name='datetime',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
    ]
