# Generated by Django 3.1.7 on 2021-05-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResearchManage', '0045_anotherdocuments_nameanotherdocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mkifirstrequestresearch',
            name='form_inf',
        ),
        migrations.RemoveField(
            model_name='mkifirstrequestresearch',
            name='form_inf_date',
        ),
        migrations.RemoveField(
            model_name='mkifirstrequestresearch',
            name='form_inf_version',
        ),
        migrations.AddField(
            model_name='anotherdocuments',
            name='date',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anotherdocuments',
            name='version',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
