# Generated by Django 3.1.7 on 2021-05-13 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserControl', '0030_auto_20210513_1343'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ResearchManage', '0047_auto_20210505_1535'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='anotherdocuments',
            table='AnotherDocuments',
        ),
        migrations.AlterModelTable(
            name='conflictsinterests',
            table='ConflictsInterests',
        ),
        migrations.AlterModelTable(
            name='logaboutresearch',
            table='logAboutResearch',
        ),
        migrations.AlterModelTable(
            name='medproductrequestresearch',
            table='MedProductRequestResearch',
        ),
        migrations.AlterModelTable(
            name='mkifirstrequestresearch',
            table='MkiFirstRequestResearch',
        ),
        migrations.AlterModelTable(
            name='nameanotherdocument',
            table='NameAnotherDocument',
        ),
        migrations.AlterModelTable(
            name='requestnumber',
            table='RequestNumber',
        ),
        migrations.AlterModelTable(
            name='requestsresearchslist',
            table='RequestsResearchsList',
        ),
        migrations.CreateModel(
            name='MkiFirstRequestResearchHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subpoena', models.FileField(upload_to='temp/')),
                ('addedInMeeting', models.BooleanField(default=False)),
                ('report', models.FileField(upload_to='temp/')),
                ('acceptedOnMeeting', models.CharField(max_length=20)),
                ('protocol_number', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('secretar_accepted', models.CharField(max_length=10)),
                ('secretar_accepted_date', models.DateField(blank=True, null=True)),
                ('date_created', models.CharField(max_length=50)),
                ('document', models.FileField(upload_to='temp/')),
                ('status', models.CharField(max_length=10)),
                ('list_members', models.FileField(upload_to='temp/')),
                ('ver_bio', models.CharField(max_length=50)),
                ('accept_research', models.FileField(blank=True, null=True, upload_to='temp/')),
                ('accept_research_version', models.CharField(blank=True, max_length=50, null=True)),
                ('accept_research_date', models.DateField(blank=True, null=True)),
                ('protocol_research', models.FileField(upload_to='temp/')),
                ('protocol_research_version', models.CharField(max_length=50)),
                ('protocol_research_date', models.DateField()),
                ('contract', models.FileField(upload_to='contract/')),
                ('contract_date', models.DateField()),
                ('advertising', models.FileField(blank=True, null=True, upload_to='temp/')),
                ('write_objects', models.FileField(blank=True, null=True, upload_to='temp/')),
                ('name_another_doc', models.CharField(blank=True, max_length=50, null=True)),
                ('another_doc', models.FileField(blank=True, null=True, upload_to='another_doc/')),
                ('another_doc_version', models.CharField(blank=True, max_length=50, null=True)),
                ('another_doc_date', models.DateField(blank=True, null=True)),
                ('datetime_edit', models.DateField(blank=True, null=True)),
                ('expert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='username_expert_h', to=settings.AUTH_USER_MODEL)),
                ('main_researcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FIOS_h', to='UserControl.pi_birthday')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_h', to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_h', to='ResearchManage.requestsresearchslist')),
            ],
            options={
                'db_table': 'MkiFirstRequestHistory',
            },
        ),
    ]
