# Generated by Django 3.1.7 on 2021-05-13 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResearchManage', '0049_historicalmkifirstrequestresearch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mkifirstrequestresearchhistory',
            name='datetime_edit',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='HistoricalMkiFirstRequestResearch',
        ),
    ]
