# Generated by Django 3.1.7 on 2021-05-13 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ResearchManage', '0051_mkifirstrequestresearchhistory_research'),
    ]

    operations = [
        migrations.AddField(
            model_name='mkifirstrequestresearchhistory',
            name='name_document',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='name_document', to='ResearchManage.nameanotherdocument'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AnotherDocuments',
        ),
    ]
