# Generated by Django 3.1.7 on 2021-05-13 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ResearchManage', '0055_anotherdocumentshistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anotherdocuments',
            name='name_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_documents', to='ResearchManage.nameanotherdocument'),
        ),
    ]
