# Generated by Django 3.1.7 on 2021-05-14 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResearchManage', '0056_auto_20210513_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='mkifirstrequestresearchhistory',
            name='ver',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
