# Generated by Django 3.1.7 on 2021-05-17 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResearchManage', '0057_mkifirstrequestresearchhistory_ver'),
    ]

    operations = [
        migrations.AddField(
            model_name='anotherdocuments',
            name='description',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anotherdocumentshistory',
            name='description',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
