# Generated by Django 3.1.3 on 2020-11-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserControl', '0002_auto_20201116_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
