# Generated by Django 3.1.3 on 2020-11-16 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserControl', '0003_auto_20201116_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role', to='UserControl.role'),
        ),
    ]
