# Generated by Django 3.1.3 on 2020-11-17 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserControl', '0004_auto_20201116_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainResearcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_researcher', to='UserControl.role')),
            ],
        ),
    ]
