# Generated by Django 3.1.3 on 2020-11-17 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserControl', '0005_mainresearcher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainresearcher',
            old_name='username',
            new_name='user',
        ),
    ]
