# Generated by Django 3.1.3 on 2020-11-17 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserControl', '0006_auto_20201117_1542'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MainResearcher',
        ),
    ]
