# Generated by Django 3.0.7 on 2020-12-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserControl', '0007_delete_mainresearcher'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='user_photo/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
    ]
