# Generated by Django 3.1.7 on 2021-02-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserControl', '0008_auto_20201229_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
