# Generated by Django 3.1.7 on 2021-03-15 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserControl', '0011_auto_20210309_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(default='Man', max_length=30),
            preserve_default=False,
        ),
    ]
