# Generated by Django 3.1.7 on 2021-03-16 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserControl', '0012_user_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
