# Generated by Django 3.1.7 on 2021-03-17 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserControl', '0013_auto_20210316_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userOwnerDocs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
