# Generated by Django 3.1.7 on 2021-03-17 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserControl', '0014_docslist'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocsTypeList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='docslist',
            name='name',
        ),
        migrations.AddField(
            model_name='docslist',
            name='docName',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='DocsType', to='UserControl.docstypelist'),
            preserve_default=False,
        ),
    ]
