# Generated by Django 3.1.7 on 2021-03-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserControl', '0015_auto_20210317_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='docStatus',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
