# Generated by Django 3.1.7 on 2021-03-23 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserControl', '0017_auto_20210323_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docslist',
            name='statuss',
        ),
    ]
