# Generated by Django 3.1.7 on 2021-03-25 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserControl', '0020_positionlist_positionuserlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='positionuserlist',
            name='status',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
