# Generated by Django 3.1.7 on 2021-04-05 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserControl', '0021_positionuserlist_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('email',)},
        ),
    ]
