# Generated by Django 3.1.7 on 2021-04-05 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserControl', '0023_filesforresearch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FilesForResearch',
        ),
    ]
