# Generated by Django 3.1.7 on 2021-04-08 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserControl', '0024_delete_filesforresearch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pi_birthday',
            name='City',
        ),
        migrations.RemoveField(
            model_name='pi_birthday',
            name='birthday',
        ),
    ]
