# Generated by Django 3.1.7 on 2021-04-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserControl', '0027_auto_20210428_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Почта'),
        ),
    ]
