# Generated by Django 3.1.7 on 2021-05-04 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserControl', '0028_auto_20210428_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.TextField(verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(max_length=10, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='registration_accepted',
            field=models.CharField(max_length=10, verbose_name='Подтвердить регистрацию'),
        ),
    ]
