# Generated by Django 3.1.3 on 2020-11-25 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetingsManage', '0004_researchlist_userlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetings',
            name='researchList',
        ),
        migrations.RemoveField(
            model_name='meetings',
            name='userList',
        ),
    ]
