# Generated by Django 3.1.3 on 2020-11-25 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetingsManage', '0005_auto_20201125_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetings',
            name='description',
        ),
        migrations.RemoveField(
            model_name='meetings',
            name='meetings',
        ),
        migrations.AlterField(
            model_name='meetings',
            name='date',
            field=models.DateField(default='2000-06-07'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meetings',
            name='time',
            field=models.CharField(max_length=100),
        ),
    ]
