# Generated by Django 3.1.7 on 2021-02-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetingsManage', '0008_auto_20201126_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchlist',
            name='status',
            field=models.CharField(default='ACCEPTED', max_length=10),
            preserve_default=False,
        ),
    ]
