# Generated by Django 3.1.7 on 2021-02-25 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetingsManage', '0009_researchlist_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchlist',
            name='status',
        ),
    ]
