# Generated by Django 3.1.7 on 2021-02-25 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetingsManage', '0010_remove_researchlist_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10)),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='VoteList', to='meetingsManage.researchlist')),
                ('username_vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='username_vote', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
