# Generated by Django 3.1.7 on 2021-02-25 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetingsManage', '0011_votelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='votelist',
            name='meeting_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='meetingsManage.meetings'),
            preserve_default=False,
        ),
    ]
