# Generated by Django 3.1.7 on 2021-02-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetingsManage', '0012_votelist_meeting_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votelist',
            name='username_vote',
            field=models.CharField(max_length=100),
        ),
    ]
