# Generated by Django 3.1.7 on 2021-02-25 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetingsManage', '0013_auto_20210225_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votelist',
            name='username_vote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='username_vote', to=settings.AUTH_USER_MODEL),
        ),
    ]
