# Generated by Django 3.1.7 on 2021-02-25 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetingsManage', '0015_auto_20210225_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votelist',
            name='research',
        ),
        migrations.AddField(
            model_name='votelist',
            name='research_id',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='votelist',
            name='meeting_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='votelist',
            name='status',
            field=models.CharField(max_length=100),
        ),
    ]
