# Generated by Django 3.1.7 on 2021-03-09 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetingsManage', '0017_expertrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetings',
            name='status',
            field=models.CharField(default='False', max_length=100),
            preserve_default=False,
        ),
    ]
