# Generated by Django 3.1.7 on 2021-03-11 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetingsManage', '0018_meetings_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votelist',
            name='research_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_id_id', to='meetingsManage.researchlist'),
        ),
    ]
