# Generated by Django 3.1.7 on 2021-03-11 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ResearchManage', '0022_auto_20210309_1425'),
        ('meetingsManage', '0019_auto_20210311_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votelist',
            name='research_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_id_vote', to='ResearchManage.mkifirstrequestresearch'),
        ),
    ]
