# Generated by Django 3.1.7 on 2021-03-19 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetingsManage', '0020_auto_20210311_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchlist',
            name='research',
            field=models.CharField(max_length=100),
        ),
    ]
