# Generated by Django 3.1.7 on 2021-03-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetingsManage', '0021_auto_20210319_1152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='researchlist',
            old_name='research',
            new_name='research_id',
        ),
        migrations.AddField(
            model_name='researchlist',
            name='research_type',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
    ]
