# Generated by Django 3.1.7 on 2021-03-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetingsManage', '0022_auto_20210319_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votelist',
            name='research_id',
            field=models.CharField(max_length=100),
        ),
    ]
