# Generated by Django 3.1.7 on 2021-03-30 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetingsManage', '0027_remove_meetings_acceptedonmeeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='votelist',
            name='datetime',
            field=models.DateTimeField(default='2021-05-06 15:47'),
            preserve_default=False,
        ),
    ]
