# Generated by Django 3.1.7 on 2021-04-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetingsManage', '0029_auto_20210330_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='votelist',
            name='message',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
