# Generated by Django 3.1.7 on 2021-04-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetingsManage', '0030_votelist_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetings',
            name='subpoena',
            field=models.FileField(default='', upload_to='temp/'),
            preserve_default=False,
        ),
    ]
