# Generated by Django 3.1.7 on 2021-03-03 08:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VoteList',
            new_name='LoggerRecords',
        ),
    ]
